name: scgpt-mechinterp
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - h5py
  - anndata
  - scanpy
  - scikit-learn
  - networkx
  - pyyaml
  - tqdm
  - matplotlib
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pip:
      - transformers
      - einops
      - lightning
      - scikit-misc
      - ipython
      - torchtext
      - datasets
      - arboreto
